spring.application.name=RaceKatteKlubben
spring.datasource.url=jdbc:mysql://localhost:3306/kattedb
spring.datasource.username=root
spring.datasource.password=Fucking8008Password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.thymeleaf.cache=false

server.port=8080